### ISSUE TITLE
Ophardt uitslag herkent uitvaller niet

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#1]
Nummer 21 is niet op komen dagen bij de eliminatie.

Waarschijnlijk moet je bij de patroonherkenning van de uitslagen alleen maar de code ABD herkennen en dan meteen naar het volgende veld springen, en bij de voornaam "(Direktausscheidung)" vervolgens er uit filteren.

[Moers 2-10-16.pdf](https://github.com/Schermen/Ranglijsten/files/560029/Moers.2-10-16.pdf)

**Comment by prwater** [comment]
Extactor is aangepast. Volgende keer zal inlezen met ADB goed gaan.
