### ISSUE TITLE
Engarde formaat niet herkend

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#11]
- Gevonden op http://www.eurofencing.info/tournaments/details/italy-busto-arsizio-2017
- Niet herkend als Engarde PDF of HTML
- PDF Grabber maakt er geen leesbare tekst van
"
$%&amp;'#( #           ))))       %&amp;#*#(&amp; + % (,#        &amp; #           -! !   ))
#$. /                  -0      1&amp;+                    &amp; #           ! -!   --
#'2#3# 3             -          ' ,                     +4           ! !   ))5
"

[Results_EF23_Busto_Arsizio.pdf](https://github.com/Schermen/Ranglijsten/files/818665/Results_EF23_Busto_Arsizio.pdf)

**Comment by CFWJansen** [comment]
Uiteindelijk handmatig bewerkt en ingevoerd als https://knas.onzeranglijsten.net/pag/31da/trn/3a9b0e.

Veel dingen nog handmatig aan moeten doen, misschien dat het daarom niet lukte.

**Comment by prwater** [comment]
Het is inderdaad een onleesbare PDF. Deze PDF is aangemaakt per PDFCreator (BTW geen fijne sotware https://en.wikipedia.org/wiki/PDFCreator).

Eens ijken of we een patroon kunnen ontdekken in onleesbare PDF-files.

```
water@sabel:~> pdfinfo Downloads/Results_EF23_Busto_Arsizio.pdf 
Title:          tireuses ordre alphbétique
Subject:        
Keywords:       
Author:         PC
Creator:        PDFCreator 2.3.0.103
Producer:       PDFCreator 2.3.0.103
CreationDate:   Mon Feb 13 15:44:22 2017 CET
ModDate:        Mon Feb 13 15:44:22 2017 CET
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
Syntax Warning: Invalid least number of objects reading page offset hints table
JavaScript:     no
Pages:          27
Encrypted:      no
Page size:      595 x 842 pts (A4)
Page rot:       0
File size:      412568 bytes
Optimized:      yes
PDF version:    1.4
```
