### ISSUE TITLE
Ophardt PDF importeert niet goed

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#14]
[51. Adolf-Ermer-Plakette.pdf](https://github.com/Schermen/Ranglijsten/files/822499/51.Adolf-Ermer-Plakette.pdf)

![screenshot](https://cloud.githubusercontent.com/assets/19391480/23629685/b745b69e-02b8-11e7-94f9-f94761b4408a.jpg)

Vanaf positie 89 gaat hij fout, er zit een paginabreak tussen maar verder kan ik geen reden ontdekken

**Comment by prwater** [comment]
Deze variant wordt nu ook herkent.
