### ISSUE TITLE
Ophardt pdf afvallers na voorronde niet herkend

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#15]
[documentation-1349-16-Foil-female-Individuel-Senior.pdf](https://github.com/Schermen/Ranglijsten/files/836785/documentation-1349-16-Foil-female-Individuel-Senior.pdf)
De eerste 56 plaatsen gaan goed, daarna niet meer.

**Comment by prwater** [comment]
Ook deze Engelse variant wordt nu herkend.
