### ISSUE TITLE
Bug 15 nog steeds niet opgelost

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#16]
Sorry dat ik dit niet eerder opnieuw geprobeerd heb, maar het probleem blijft. Ik gebruik de PDF uit GitHub, maar hij gaat weer op hetzelfde punt fout.

**Comment by prwater** [comment]
Hmm, blijkbaar had ik de update nog niet geïnstalleerd. Nu gaat het wel goed.
