### ISSUE TITLE
Ophardt leest niet goed in vanwege tweede voorronde

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#2]
Posities 91-108 met de hand moeten corrigeren. Het lijkt er op dat hij niet overweg kan met de tweede voorronde.
[Nord-Ostsee-Pokal 2016.pdf](https://github.com/Schermen/Ranglijsten/files/560133/Nord-Ostsee-Pokal.2016.pdf)

**Comment by CFWJansen** [comment]
.

**Comment by prwater** [comment]
In de bijlage is de convocatie, niet de uitslag. Kun je alsnog de uitslag toevoegen?

**Comment by CFWJansen** [comment]
Dit is de uitslag.

[Uitslag JQB Nord-Ostsee-Pokal Bad Segeberg 2016 (1).pdf](https://github.com/Schermen/Ranglijsten/files/560339/Uitslag.JQB.Nord-Ostsee-Pokal.Bad.Segeberg.2016.1.pdf)

**Comment by CFWJansen** [comment]
Beste Paul,

Volgens mij heb ik geen rechten om het terug op jouw naam te zetten.

Groet,

Christian

Op zo 30 okt. 2016 om 08:16 schreef P.R. Water <notifications@github.com>:

**Comment by prwater** [comment]
Opgelost. 

Nieuwe release staat op productie.
