### ISSUE TITLE
Resultaten NK Equipe invoeren lukt niet

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#20]
Verschillende mensen hebben op diverse manieren geprobeerd de resultaten van het NK Equipe in te voeren.

Helaas lukt het niet. Ook niet als ik je de xml files probeert te importeren.

Hoe zouden de resultaten ingevoerd moeten worden?

**Comment by prwater** [comment]
Kan iemand mij de bestanden toe sturen?

**Comment by OscarKardolus** [comment]
xml bestanden toegevoegd (hoop ik)

Het werkt ook niet als je alles met de hand wil invoeren. 

Het systeem vraagt om individuele namen en nummers

**Comment by OscarKardolus** [comment]
[NKQ2017.ZIP](https://github.com/Schermen/Ranglijsten/files/1141780/NKQ2017.ZIP)

**Comment by prwater** [comment]
Probleem is verholpen.
