### ISSUE TITLE
Navigatiepijltjes ontbreken na genereren van een ranglijst

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#21]
Na het generen van een ranglijst verschijnen de navigatie pijltjes boven aan de pagina niet meer om makkelijk van de ene naar de andere categorie te navigeren,

Hopelijk heb ik het duidelijk genoeg verwoord...

Zonder die pijtjes kost het genereren van de ranglijsten enorm veel tijd

**Comment by prwater** [comment]
Pijltjes zijn weer terug.
