### ISSUE TITLE
Seizoen 2017/2018 geblokkeerd ?

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#22]
Het lijkt er op dat er iets geblokkeerd is

Het lukt niet op wedstrijden toe te voegen en ook niet om nieuwe ranglijsten te genereren

Moet er nog aanpassingen gedaan worden voor het nieuwe seizoen ?

**Comment by prwater** [comment]
Elk seizoen moet een nieuwe subsysteem worden aangemaakt. Dit heb ik zojuist gedaan door het vorige subsysteem te kopiëren.

Nu moet het volgende nog gebeuren:
* Eventueel moeten de deelnemersconstanten worden aangepast. Jij kunt dit doen op https://knas.onzeranglijsten.net/pag/adf/sss/cac9.
* De wereldranglijsten moeten worden geüpload. Jij kunt dit doen op https://knas.onzeranglijsten.net/pag/ddd3/sss/f8c8. Tip: maak gebruik van de FIE-grijper: https://knas.onzeranglijsten.net/pag/addd/sss/cac9

**Comment by OscarKardolus** [comment]
Heb de meeste wereldranglijsten kunnen importeren. 4 lukten er echter niet :-(
- Floret Dames Senioren
- Sabel Heren Junioren
- Degen Heren Junioren
- Degen Dames Junioren
[WB2016-2017-ImportNietGelukt.zip](https://github.com/Schermen/Ranglijsten/files/1202202/WB2016-2017-ImportNietGelukt.zip)

De betreffende files heb ik bijgevoegd

**Comment by OscarKardolus** [comment]
Heb de indruk dat het te maken heeft met de lengte van de namen....

**Comment by OscarKardolus** [comment]
En nu lukt het nog steeds niet om een wedstrijd in te voeren die gehouden is in juli. 

De handmatige invoer lijkt wel te lukken maar zodra ik op de knop [Wedstrijd] druk om de details in te vullen komt de volgende melding in beeld :
![image](https://user-images.githubusercontent.com/19303081/28994110-4111e422-79c6-11e7-9be2-ab4a407caf9a.png)
