### ISSUE TITLE
Definitie Seizoenen

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#23]
Ik zag toevallig de definities van de seizoenen op pagina : https://knas.onzeranglijsten.net/pag/22b1

Er is nu ingevuld dat de seizoenen lopen van 1-9 t/m 31-8. Het zou moeten zijn 1-8 t/m 31-7

Helaas lukt het me niet om de data aan te passen

**Comment by prwater** [comment]
Seizoen zijn aangepast.
