### ISSUE TITLE
Importeren Wereldranglijsten

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#24]
Heb de meeste wereldranglijsten kunnen importeren. 4 lukten er echter niet :-(

- Floret Dames Senioren
- Sabel Heren Junioren
- Degen Heren Junioren
- Degen Dames Junioren

Heb de indruk dat het te maken heeft met de lengte van de namen....

[WB2016-2017-ImportNietGelukt.zip](https://github.com/Schermen/Ranglijsten/files/1202491/WB2016-2017-ImportNietGelukt.zip)

**Comment by prwater** [comment]
Ik heb 1 issue opgelost. Ik verwacht dat je ze nu allemaal op 1 na kunt importeren.

**Comment by OscarKardolus** [comment]
2 lukken er nog niet
- Sabel Heren Junioren
- Floret Dames Senioren

**Comment by prwater** [comment]
Die kun je nogmaals proberen.

**Comment by prwater** [comment]
Blijkbaar gelukt.
