### ISSUE TITLE
Totaal aantal punten op ranglijsten klopt niet meer

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#25]
Nadat ik een aantal ranglijsten van 1-8 gegenereerd had merkte ik dat een aantal schermers flink veel punten meer hadden ten opzichte van de ranglijst van 1-7.

Na enig rekenwerk blijkt dat voor het totaal aantal punten niet meer de hoogste 5 aantallen worden geteld maar dat alle behaalde punten bij alle wedstrijden worden opgeteld.

Dat kan toch niet kloppen lijkt mij

**Comment by prwater** [comment]
Opgelost. Wel even de ranglijsten opnieuw genereren en publiceren.
