### ISSUE TITLE
Engarde PDF Luzern niet herkend

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#26]
[917717.pdf luzern.pdf](https://github.com/Schermen/Ranglijsten/files/1346418/917717.pdf.luzern.pdf)

Krijg foutmelding bij het importeren

**Comment by OscarKardolus** [comment]
Ik heb de Duitse tekst boven de einduitslag veranderd in 'Classement Général' en toen kon ik wel wat met de file
