### ISSUE TITLE
Allemaal HUN bij invoer wedstrijd

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#3]
Er gebeurt iets raars ij de verwerking van bijgaande uitslag in pdf.

Als ik op het tabblad deelnemers kom staat er bij iedereen HUN. 

[Budapest-DegenHeren-ECC-2016.pdf](https://github.com/Schermen/Ranglijsten/files/560377/Budapest-DegenHeren-ECC-2016.pdf)

Volgens mij staat het goed in de pdf.

Kan jij svp uitzoeken wat er aan de hand is ?

**Comment by OscarKardolus** [comment]
Bij deze wedstrijd gebeurt hetzelfde

[Godollo-SabelHeren-ECC-2016.pdf](https://github.com/Schermen/Ranglijsten/files/560378/Godollo-SabelHeren-ECC-2016.pdf)

**Comment by prwater** [comment]
@OscarKardolus Graag 1 probleem (in dit geval pdf) per issue in het vervolg.

Deze problemen zijn opgelost.

**Comment by prwater** [comment]
BTW. Bij het opnieuw inlezen van de pdf moet je niet de wedstrijd eerst verwijderen, maar via het potloodje de pdf opnieuw inlezen.

**Comment by OscarKardolus** [comment]
Nu gaat het goed :-)
