### ISSUE TITLE
Import met FIE grijper gaat fout

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#4]
Het gaat om de volgende wedstrijd

http://fie.org/competitions/2017/382/results/rank

De volgende foutmelding verschijnt

De pagina op knas.onzeranglijsten.net werkt niet

knas.onzeranglijsten.net kan dit verzoek momenteel niet verwerken.

**Comment by prwater** [comment]
Op dit moent is deze uitslag nog een voorlopige uitslag. Blijkbaar kan het dan voorkomen dat een schermer dan nog geen "eigen" pagina heeft waardoor ik geen licentienummer kan afleiden. Op dit moment heeft nummer 132, BRZEZINSKI Jan, geen eiegen pagina.

Ik heb nu ondervangen dat een deelnemer geen eigen pagina heeft.
