### ISSUE TITLE
Gemengde wedstrijden

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#5]
De berekening van gemengde wedstrijden voor de dames gaat fout.

Bij het selecteren van de wedstrijden staat de gemengde wedstrijd er wel tussen maar wordt toch niet meegenomen in de berekening. Ook de resultaten verschijnen niet in de kolom die wel getoond wordt.

Wedstrijden waar dit oa voor geldt zijn Zilveren Wapens Floret en Ferrum Vetum 2016-4 Floret.

ps Als ik de betreffende wedstrijden in een wedstrijd voor dames verander gaat het voor de dames wel goed.

**Comment by prwater** [comment]
Issue is verholpen. Ik heb de geraakte ranglijsten opnieuw berekend.
