### ISSUE TITLE
Ophardt equipe uitslag deelnemers niet herkend

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#6]
[13242.pdf](https://github.com/Schermen/Ranglijsten/files/579221/13242.pdf)

Bij deze uitslag worden de deelnemers niet herkend. Hij ziet wel dat het 11 equipes zijn, maar pakt de individuele eindlijst niet.

**Comment by prwater** [comment]
In deze pdf staan 4 uitslagen (er is dus geen sprake van **de** individuele eindlijst):
* Equipe meisjes
* Individueel meisjes
* Equipe jongens
* Individueel jongens

De pdf extractor kan maar 1 uitslag per pdf aan (dit zal ook zo blijven). Ik denk dat de oplossing voor de pdf is om de pagina's met 2 individuele uitslagen met een pdf tool op te slaan in 2 aparte pdfs en deze op de gebruikelijke manier in te lezen.
