### ISSUE TITLE
WB FIE Grijper foutmelding bij deelnemers

### ISSUE THREAD

**Issue by CFWJansen** [Schermen/Ranglijsten#8]
Ik krijg een foutmelding bij het toevoegen via de FIE Grijper.
1. Methode: FIE Grijper
2. URL: http://fie.org/competitions/2017/441/results/rank#
3. Wedstrijdgegevens OK
4. Druk op groene pijl links van deelnemers
5. Foutmelding:

errorDe door u opgevraagde pagina op OnzeRanglijsten is niet gevonden. Dit kan één van de onderstaande oorzaken hebben:
U heeft een pagina of gegevens opgevraagd opgevraagd waarvoor u niet of niet langer de juiste autorisatie heeft.
U heeft foutieve link of en link die niet langer geldig is gebruikt.
Vanuit veiligheidsoverwegingen wordt de exacte oorzaak niet getoond.

De webmaster wordt automatisch op de hoogte gebracht.

**Comment by CFWJansen** [comment]
Update: Ophardt PDF lijkt het ook niet te doen. Handmatig wel

**Comment by OscarKardolus** [comment]
Bij mij gaat de invoer met de FIE grijper prima

**Comment by prwater** [comment]
Daar het Oscar wel is gelukt, sluit ik dit issue.

Mocht dit nogmaals voorkomen, even uit en inloggen, dan is het probleem verholpen.

**Comment by CFWJansen** [comment]
Hij is weer opnieuw opgetreden. Het lijkt te gebeuren nadat ik een PDF upload, er achter kom dat het de verkeerde was en daarna een andere PDF probeer te uploaden. Uitloggen en inloggen heeft geen resultaat, rebooten ook niet en client cache legen ook niet.

Kun jij iets in de server logs zien? Volgens het scherm heb je er een mailtje over gehad. Een paar zelfs, want ik heb het meerdere keren geprobeerd.

**Comment by prwater** [comment]
Deze storing heeft niets te maken met de FIE grijper, je probeert een Engarde uitslag in te lezen.

Kun je deze uitslag naar mij mailen? Dan kan ik zien wat er aan mankeert.
