### ISSUE TITLE
Vorige versie wedstrijd indien er geen 'oude'wedstrijden in de betreffende categorie zijn

### ISSUE THREAD

**Issue by OscarKardolus** [Schermen/Ranglijsten#9]
Als je een wedstrijd toevoegt er zijn in de betreffende categorie geen 'oude' wedstrijden loop je bij het selecteren van de vorige vorige versie vast. Je komt in een scherm waar je niet meer uit komt.

Zie het plaatje 

![image](https://cloud.githubusercontent.com/assets/19303081/23339424/7db4b836-fc22-11e6-9cde-161c06a31e2b.png)

**Comment by OscarKardolus** [comment]
Dit heb ik nu ervaren met 4 verschillende categorieën

**Comment by prwater** [comment]
Bij welke wedstrijd? Heb je voor de uitslag zodat ik dit issue kan reproduceren?

**Comment by OscarKardolus** [comment]
[DD4.zip](https://github.com/Schermen/Ranglijsten/files/802900/DD4.zip)

Zoals gevraag een voorbeeld file

**Comment by prwater** [comment]
Fixed!
